# -*- coding: utf-8 -*-
"""session-15-numpy-tricks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUW-yXxbkSYgvlhC5_zf30aOVyKYo9AC

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html
"""

# code
import numpy as np
a = np.random.randint(1,100,15)
a

b = np.random.randint(1,100,24).reshape(6,4)
b

np.sort(a)[::-1]

np.sort(b,axis=0)

"""### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html
"""

# code
np.append(a,200)

b

np.append(b,np.random.random((b.shape[0],1)),axis=1)

"""### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
"""

# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

np.concatenate((c,d),axis=0)

np.concatenate((c,d),axis=1)

"""### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/
"""

# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

np.unique(e)

"""### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html
"""

# code
a.shape

np.expand_dims(a,axis=0).shape

np.expand_dims(a,axis=1)

"""### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html
"""

a

# find all indices with value greater than 50
np.where(a>50)

# replace all values > 50 with 0
np.where(a>50,0,a)

np.where(a%2 == 0,0,a)

"""### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
"""

# code
a

np.argmax(a)

b

np.argmax(b,axis=0)

np.argmax(b,axis=1)

# np.argmin
np.argmin(a)

"""### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html
"""

a

np.cumsum(a)

b

np.cumsum(b,axis=1)

np.cumsum(b)

# np.cumprod
np.cumprod(a)

a

"""### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
"""

a

np.percentile(a,50)

np.median(a)

"""### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html
"""

# code
a

np.histogram(a,bins=[0,50,100])

"""### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
"""

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

"""### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html
"""

# code
a

items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

"""### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html
"""

# code
a

np.flip(a)

b

np.flip(b,axis=1)

"""### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html
"""

# code
a

np.put(a,[0,1],[110,530])

"""### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html
"""

# code
a

np.delete(a,[0,2,4])

"""### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d
"""

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

np.intersect1d(m,n)

np.setdiff1d(n,m)

np.setxor1d(m,n)

m[np.in1d(m,1)]

"""### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html
"""

# code
a

np.clip(a,a_min=25,a_max=75)

# 17. np.swapaxes

# 18. np.uniform

# 19. np.count_nonzero

# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

# 25. np.allclose and equals











